import { defineConfig, type DefaultTheme } from 'vitepress'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

type SidebarItem = DefaultTheme.SidebarItem

/**
 * Parse a generated TypeDoc markdown page and extract member names.
 * If `groupHeading` is provided, only extract members under that `## Group` section.
 * Returns sidebar items linking to the member anchors on that page.
 */
function extractMethodLinks(mdPath: string, baseLinkPath: string, groupHeading?: string): SidebarItem[] {
  try {
    const content = readFileSync(resolve(__dirname, '..', mdPath), 'utf-8')
    let text = content
    if (groupHeading) {
      // Extract only the section under the given ## heading
      const sectionRegex = new RegExp(`^## ${groupHeading}$`, 'm')
      const start = text.search(sectionRegex)
      if (start === -1) return []
      text = text.slice(start)
      // Trim at the next ## heading
      const nextSection = text.indexOf('\n## ', 1)
      if (nextSection !== -1) text = text.slice(0, nextSection)
    }
    const memberRegex = /^### (\w+)(\(\))?$/gm
    const items: SidebarItem[] = []
    let match: RegExpExecArray | null
    while ((match = memberRegex.exec(text)) !== null) {
      const name = match[1]
      const isMethod = !!match[2]
      items.push({
        text: isMethod ? `${name}()` : name,
        link: `${baseLinkPath}#${name.toLowerCase()}`,
      })
    }
    return items
  } catch {
    return []
  }
}

function readGeneratedReferenceTree(): SidebarItem[] {
  // Generated by scripts/gen-reference-index.mjs
  const p = resolve(__dirname, 'generated/reference-nav.json')
  try {
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw) as { items?: SidebarItem[] }
    return parsed.items ?? []
  } catch {
    return []
  }
}

function findChild(node: SidebarItem, text: string): SidebarItem | undefined {
  return node.items?.find((i) => i.text === text)
}

function normalizeTitle(s: string | undefined): string {
  return (s ?? '').replace(/\s+/g, ' ').trim()
}

function buildReferenceSidebar(tree: SidebarItem[]): SidebarItem[] {
  // Desired order:
  // - primitive-app
  // - js-bao-wss-client
  // - js-bao
  const byName = new Map(tree.map((t) => [t.text, t]))

  const primitive = byName.get('primitive-app')
  const wss = byName.get('js-bao-wss-client')
  const bao = byName.get('js-bao')

  function pickTypedocApiSections(
    projectNode: SidebarItem | undefined,
    sectionTitles: string[]
  ): SidebarItem[] {
    const api = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'api')
    if (!api) return []

    const out: SidebarItem[] = []
    for (const title of sectionTitles) {
      const section = api.items?.find(
        (i) => normalizeTitle(i.text).toLowerCase() === title.toLowerCase()
      )
      if (section) out.push({ text: title, items: section.items ?? [], collapsed: true })
    }
    return out
  }

  function pickWssClientSections(projectNode: SidebarItem | undefined): SidebarItem[] {
    const api = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'api')
    if (!api) return []

    // Build a lookup of all generated interface/class pages by name
    const interfacesSection = api.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'interfaces')
    const classesSection = api.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'classes')
    const allItems = [...(interfacesSection?.items ?? []), ...(classesSection?.items ?? [])]
    const byName = new Map(allItems.map((i) => [normalizeTitle(i.text), i]))

    function pick(name: string): SidebarItem | undefined {
      return byName.get(name)
    }

    // Sections with `apis` expand each interface's methods as top-level links,
    // with `types` under a "Types" subsection.
    // `clientGroups` extracts methods from ## group sections in JsBaoClient.md.
    // Sections with only `items` list pages directly (flat).
    type DomainSection =
      | { text: string; items: string[] }
      | { text: string; apis?: string[]; clientGroups?: string[]; types: string[] }
    const domainSections: DomainSection[] = [
      {
        text: 'Client Setup',
        items: ['JsBaoClientOptions', 'JsBaoEvents'],
      },
      {
        text: 'Documents',
        apis: ['DocumentsAPI', 'DocumentContext'],
        types: ['DocumentInfo', 'DocumentPermissionEntry',
          'DocumentGroupPermissionEntry', 'DocumentInvitation', 'DocumentInvitationResponse',
          'DocumentAccessResult', 'DocumentCollectionInfo'],
      },
      {
        text: 'Databases',
        apis: ['DatabasesAPI'],
        types: ['DatabaseInfo', 'DatabasePermissionEntry',
          'DatabaseOwnershipTransferResult', 'DatabaseOperationInfo',
          'CsvImportOptions', 'CsvImportProgress', 'CsvImportResult'],
      },
      {
        text: 'Collections',
        apis: ['CollectionsAPI'],
        types: ['CollectionInfo', 'CollectionDocumentInfo',
          'CollectionGroupPermissionInfo', 'CollectionMemberInfo', 'CollectionAccessInfo'],
      },
      {
        text: 'Users & Groups',
        apis: ['UsersAPI', 'MeAPI', 'SessionAPI', 'GroupsAPI', 'GroupTypeConfigsAPI'],
        types: ['BasicUserInfo', 'UserProfile', 'SessionInfo',
          'GroupInfo', 'GroupMemberInfo', 'GroupMembershipInfo', 'GroupDocumentInfo',
          'GroupTypeConfigInfo'],
      },
      {
        text: 'Authentication',
        clientGroups: ['Authentication'],
        types: ['AuthError', 'AuthStateEvent', 'JsBaoError'],
      },
      {
        text: 'Workflows',
        apis: ['WorkflowsAPI'],
        types: ['StartWorkflowOptions', 'StartWorkflowResult',
          'GetWorkflowStatusOptions', 'WorkflowStatusResult', 'WorkflowRun',
          'ListWorkflowRunsOptions', 'ListWorkflowRunsResult',
          'TerminateWorkflowOptions', 'WorkflowDefineOptions',
          'ClaimApplyOptions', 'ClaimApplyResult',
          'ConfirmApplyOptions', 'ConfirmApplyResult',
          'ReleaseApplyOptions', 'ReleaseApplyResult',
          'WorkflowStatusEvent', 'WorkflowStartedEvent'],
      },
      {
        text: 'Prompts',
        apis: ['PromptsAPI'],
        types: ['ExecutePromptOptions', 'ExecutePromptResult'],
      },
      {
        text: 'AI / LLM',
        apis: ['GeminiAPI', 'LlmAPI'],
        types: ['LlmChatOptions',
          'GeminiPromptOptions', 'GeminiGenerateResult', 'GeminiModelSummary',
          'GeminiMessage', 'GeminiStructuredOutput', 'GeminiGenerateRawOptions'],
      },
      {
        text: 'Integrations',
        apis: ['IntegrationsAPI'],
        types: ['IntegrationCallRequest', 'IntegrationCallResponse'],
      },
      {
        text: 'Analytics',
        apis: ['AnalyticsClient'],
        types: ['AnalyticsAutoEventsOptions', 'AnalyticsEventInput'],
      },
      {
        text: 'Blobs & Files',
        apis: ['DocumentBlobContext'],
        types: ['BlobUploadSourceOptions', 'BlobUploadResult',
          'BlobListResult', 'BlobUploadStatus', 'BlobReadOptions', 'BlobPrefetchOptions',
          'BlobProxyUrlOptions',
          'BlobUploadProgressEvent', 'BlobUploadCompletedEvent', 'BlobUploadFailedEvent'],
      },
      {
        text: 'Offline & Cache',
        apis: ['CacheFacade'],
        types: ['StorageProvider'],
      },
      {
        text: 'Rule Sets',
        apis: ['RuleSetsAPI'],
        types: ['RuleSetInfo', 'RuleSetSchema',
          'RuleSetTestResult', 'RuleSetDebugResult', 'TraceEntry',
          'TriggerDefInfo', 'ModelRulesInfo'],
      },
    ]

    const claimed = new Set<string>()
    const out: SidebarItem[] = []

    const clientClassLink = '/reference/js-bao-wss-client/api/classes/JsBaoClient'
    const clientClassMdPath = 'reference/js-bao-wss-client/api/classes/JsBaoClient.md'

    for (const section of domainSections) {
      if ('types' in section) {
        // Expanded section: extract methods from APIs and/or client groups, types as subsection
        const sectionItems: SidebarItem[] = []

        // Methods from sub-API interfaces
        for (const apiName of section.apis ?? []) {
          const apiItem = pick(apiName)
          if (!apiItem?.link) continue
          claimed.add(apiName)

          const mdRelPath = `reference/js-bao-wss-client/api/interfaces/${apiName}.md`
          const methodLinks = extractMethodLinks(mdRelPath, apiItem.link)
          sectionItems.push(...methodLinks)
        }

        // Methods from JsBaoClient @group sections
        for (const group of section.clientGroups ?? []) {
          const methodLinks = extractMethodLinks(clientClassMdPath, clientClassLink, group)
          sectionItems.push(...methodLinks)
        }

        // Add Types subsection
        const typeItems: SidebarItem[] = []
        for (const name of section.types) {
          const item = pick(name)
          if (item) {
            typeItems.push(item)
            claimed.add(name)
          }
        }
        if (typeItems.length) {
          sectionItems.push({ text: 'Types', items: typeItems, collapsed: true })
        }

        if (sectionItems.length) {
          out.push({ text: section.text, items: sectionItems, collapsed: true })
        }
      } else {
        // Flat section: list pages directly
        const sectionItems: SidebarItem[] = []
        for (const name of section.items) {
          const itemName = typeof name === 'string' ? name : normalizeTitle(name.text)
          const item = pick(itemName)
          if (item) {
            sectionItems.push(item)
            claimed.add(itemName)
          }
        }
        if (sectionItems.length) {
          out.push({ text: section.text, items: sectionItems, collapsed: true })
        }
      }
    }

    // Catch any unclaimed interfaces/types in an "Other Types" section
    const unclaimed: SidebarItem[] = []
    for (const item of interfacesSection?.items ?? []) {
      if (!claimed.has(normalizeTitle(item.text))) unclaimed.push(item)
    }
    if (unclaimed.length) {
      out.push({ text: 'Other Types', items: unclaimed, collapsed: true })
    }

    return out
  }

  function pickPrimitiveApp(projectNode: SidebarItem | undefined): SidebarItem[] {
    const overview = projectNode?.items?.find(
      (i) => normalizeTitle(i.text).toLowerCase() === 'overview'
    )
    const componentsSection = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'components')
    // vue-docgen outputs under /components/** with an extra "Components" folder layer.
    const componentsRoot = componentsSection ? findChild(componentsSection, 'Components') : undefined

    const out: SidebarItem[] = []

    // Top-level pages (hand-authored): show them directly above Components.
    // These are discovered via scripts/gen-reference-index.mjs and grouped under "Overview" in the generated tree.
    if (overview?.items?.length) out.push(...overview.items)

    // Components
    const comps = componentsRoot
      ? [{ text: 'Components', items: componentsRoot.items ?? [], collapsed: true }]
      : []

    // Layouts (from vue-docgen "layouts" folder)
    const layoutsFolder = componentsSection?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'layouts')
    const layouts = layoutsFolder
      ? [{ text: 'Layouts', items: layoutsFolder.items ?? [], collapsed: true }]
      : []

    // Pages (from vue-docgen "pages" folder)
    const pagesFolder = componentsSection?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'pages')
    const pages = pagesFolder
      ? [{ text: 'Pages', items: pagesFolder.items ?? [], collapsed: true }]
      : []

    // Utils (hand-authored reference docs under docs/reference/primitive-app/utils)
    const utils = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'utils')

    // Composables (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const composables = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'composables')

    // Stores (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const stores = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'stores')

    // Services (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const services = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'services')

    // Router (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const router = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'router')

    // Config (hand-authored docs under docs/reference/primitive-app/config)
    const config = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'config')

    out.push(...comps)
    out.push(...layouts)
    out.push(...pages)
    if (services?.items?.length) out.push(...services.items)
    if (router) out.push({ text: 'Router', items: router.items ?? [], collapsed: true })
    if (utils) out.push({ text: 'Utils', items: utils.items ?? [], collapsed: true })
    if (composables)
      out.push({ text: 'Composables', items: composables.items ?? [], collapsed: true })
    if (config) out.push({ text: 'Config', items: config.items ?? [], collapsed: true })

    return out
  }

  const items: SidebarItem[] = []

  if (primitive)
    items.push({ text: 'primitive-app', items: pickPrimitiveApp(primitive), collapsed: true })
  if (wss)
    items.push({
      text: 'js-bao-wss-client',
      items: pickWssClientSections(wss),
      collapsed: true,
    })
  if (bao)
    items.push({
      text: 'js-bao',
      items: pickTypedocApiSections(bao, ['Classes', 'Functions', 'Interfaces', 'Type Aliases']),
      collapsed: true,
    })

  return items
}

export default defineConfig({
  lang: 'en-US',
  title: 'Primitive Docs',
  description: 'Unified documentation for Primitive Labs libraries and apps.',

  // GitHub Repo Pages: https://primitive-labs.github.io/primitive-docs/
  base: '/primitive-docs/',

  themeConfig: {
    // Best default: built-in local search (no external service, no API keys).
    // If we later want Algolia DocSearch, switch provider to 'algolia' and add credentials.
    search: {
      provider: 'local',
    },

    nav: [{ text: 'Docs', link: '/' }],

    // Single unified sidebar for the entire site
    sidebar: [
      {
        text: 'Getting Started',
        items: [
          { text: 'Overview', link: '/' },
          { text: 'Starting with the Template App', link: '/getting-started/template-app' },
          { text: 'Deploying to Production', link: '/getting-started/deploying-to-production' },
          { text: 'Example Apps', link: '/getting-started/example-apps' },
        ],
        collapsed: false,
      },
      {
        text: 'Users and Auth',
        items: [
          { text: 'Authentication', link: '/getting-started/authentication' },
          { text: 'Users and Groups', link: '/getting-started/users-and-groups' },
        ],
        collapsed: false,
      },
      {
        text: 'Data Persistence',
        items: [
          { text: 'Choosing Your Data Model', link: '/getting-started/choosing-your-data-model' },
          { text: 'Working with Documents', link: '/getting-started/working-with-documents' },
          { text: 'Working with Databases', link: '/getting-started/working-with-databases' },
          { text: 'Blobs and Files', link: '/getting-started/blobs-and-files' },
        ],
        collapsed: false,
      },
      {
        text: 'Platform Services',
        items: [
          { text: 'Workflows and Prompts', link: '/getting-started/workflows-and-prompts' },
          { text: 'API Integrations', link: '/getting-started/api-integrations' },
        ],
        collapsed: false,
      },
      {
        text: 'Tools',
        items: [
          { text: 'Admin Console', link: '/getting-started/admin-console' },
          { text: 'Primitive CLI', link: '/getting-started/primitive-cli' },
          { text: 'Dev Tools', link: '/getting-started/devtools' },
        ],
        collapsed: false,
      },
      {
        text: 'Changelog',
        link: '/getting-started/changelog',
      },
      {
        text: 'Reference',
        items: buildReferenceSidebar(readGeneratedReferenceTree()),
        collapsed: false,
      },
    ],

    socialLinks: [{ icon: 'github', link: 'https://github.com/Primitive-Labs/primitive-docs' }],
  },
})


