import { defineConfig } from 'vitepress'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

type SidebarItem = { text: string; link?: string; items?: SidebarItem[] }

function readGeneratedReferenceSidebar(): SidebarItem[] {
  // Generated by scripts/gen-reference-index.mjs
  const p = resolve(__dirname, 'generated/reference-nav.json')
  try {
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw) as { items?: SidebarItem[] }
    return parsed.items ?? []
  } catch {
    return []
  }
}

export default defineConfig({
  lang: 'en-US',
  title: 'Primitive Docs',
  description: 'Unified documentation for Primitive Labs libraries and apps.',

  // GitHub Repo Pages: https://primitive-labs.github.io/primitive-docs/
  base: '/primitive-docs/',

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/' },
      { text: 'Reference', link: '/reference/' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Overview', link: '/guide/' },
            // Add more manual guide pages here.
          ],
        },
      ],
      '/reference/': [
        { text: 'Reference', items: [{ text: 'Index', link: '/reference/' }, ...readGeneratedReferenceSidebar()] },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/Primitive-Labs/primitive-docs' }],
  },
})


