import { defineConfig, type DefaultTheme } from 'vitepress'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

type SidebarItem = DefaultTheme.SidebarItem

function readGeneratedReferenceTree(): SidebarItem[] {
  // Generated by scripts/gen-reference-index.mjs
  const p = resolve(__dirname, 'generated/reference-nav.json')
  try {
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw) as { items?: SidebarItem[] }
    return parsed.items ?? []
  } catch {
    return []
  }
}

function findChild(node: SidebarItem, text: string): SidebarItem | undefined {
  return node.items?.find((i) => i.text === text)
}

function normalizeTitle(s: string | undefined): string {
  return (s ?? '').replace(/\s+/g, ' ').trim()
}

function buildReferenceSidebar(tree: SidebarItem[]): SidebarItem[] {
  // Desired order:
  // - primitive-app
  // - js-bao-wss-client
  // - js-bao
  const byName = new Map(tree.map((t) => [t.text, t]))

  const primitive = byName.get('primitive-app')
  const wss = byName.get('js-bao-wss-client')
  const bao = byName.get('js-bao')

  function pickTypedocApiSections(
    projectNode: SidebarItem | undefined,
    sectionTitles: string[]
  ): SidebarItem[] {
    const api = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'api')
    if (!api) return []

    const out: SidebarItem[] = []
    for (const title of sectionTitles) {
      const section = api.items?.find(
        (i) => normalizeTitle(i.text).toLowerCase() === title.toLowerCase()
      )
      if (section) out.push({ text: title, items: section.items ?? [], collapsed: true })
    }
    return out
  }

  function pickPrimitiveApp(projectNode: SidebarItem | undefined): SidebarItem[] {
    const overview = projectNode?.items?.find(
      (i) => normalizeTitle(i.text).toLowerCase() === 'overview'
    )
    const componentsSection = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'components')
    // vue-docgen outputs under /components/** with an extra "Components" folder layer.
    const componentsRoot = componentsSection ? findChild(componentsSection, 'Components') : undefined

    const out: SidebarItem[] = []

    // Top-level pages (hand-authored): show them directly above Components.
    // These are discovered via scripts/gen-reference-index.mjs and grouped under "Overview" in the generated tree.
    if (overview?.items?.length) out.push(...overview.items)

    // Components
    const comps = componentsRoot
      ? [{ text: 'Components', items: componentsRoot.items ?? [], collapsed: true }]
      : []

    // Layouts (from vue-docgen "layouts" folder)
    const layoutsFolder = componentsSection?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'layouts')
    const layouts = layoutsFolder
      ? [{ text: 'Layouts', items: layoutsFolder.items ?? [], collapsed: true }]
      : []

    // Pages (from vue-docgen "pages" folder)
    const pagesFolder = componentsSection?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'pages')
    const pages = pagesFolder
      ? [{ text: 'Pages', items: pagesFolder.items ?? [], collapsed: true }]
      : []

    // Utils (hand-authored reference docs under docs/reference/primitive-app/utils)
    const utils = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'utils')

    // Composables (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const composables = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'composables')

    // Stores (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const stores = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'stores')

    // Services (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const services = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'services')

    // Router (generated by scripts/gen-primitive-app-ts-reference.mjs)
    const router = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'router')

    // Config (hand-authored docs under docs/reference/primitive-app/config)
    const config = projectNode?.items?.find((i) => normalizeTitle(i.text).toLowerCase() === 'config')

    out.push(...comps)
    out.push(...layouts)
    out.push(...pages)
    if (services) out.push({ text: 'Services', items: services.items ?? [], collapsed: true })
    if (router) out.push({ text: 'Router', items: router.items ?? [], collapsed: true })
    if (utils) out.push({ text: 'Utils', items: utils.items ?? [], collapsed: true })
    if (composables)
      out.push({ text: 'Composables', items: composables.items ?? [], collapsed: true })
    if (config) out.push({ text: 'Config', items: config.items ?? [], collapsed: true })

    return out
  }

  const items: SidebarItem[] = []

  if (primitive)
    items.push({ text: 'primitive-app', items: pickPrimitiveApp(primitive), collapsed: true })
  if (wss)
    items.push({
      text: 'js-bao-wss-client',
      items: pickTypedocApiSections(wss, ['Classes', 'Functions', 'Interfaces', 'Type Aliases']),
      collapsed: true,
    })
  if (bao)
    items.push({
      text: 'js-bao',
      items: pickTypedocApiSections(bao, ['Classes', 'Functions', 'Interfaces', 'Type Aliases']),
      collapsed: true,
    })

  return items
}

export default defineConfig({
  lang: 'en-US',
  title: 'Primitive Docs',
  description: 'Unified documentation for Primitive Labs libraries and apps.',

  // GitHub Repo Pages: https://primitive-labs.github.io/primitive-docs/
  base: '/primitive-docs/',

  themeConfig: {
    // Best default: built-in local search (no external service, no API keys).
    // If we later want Algolia DocSearch, switch provider to 'algolia' and add credentials.
    search: {
      provider: 'local',
    },

    nav: [{ text: 'Docs', link: '/' }],

    // Single unified sidebar for the entire site
    sidebar: [
      {
        text: 'Getting Started',
        items: [
          { text: 'Overview', link: '/' },
          { text: 'Example Apps', link: '/getting-started/example-apps' },
          { text: 'Starting with the Template App', link: '/getting-started/template-app' },
          { text: 'The Local-First Model', link: '/getting-started/local-first-model' },
          { text: 'Understanding Documents', link: '/getting-started/understanding-documents' },
          { text: 'Working with Data', link: '/getting-started/working-with-data' },
          { text: 'Other Services', link: '/getting-started/other-services' },
          { text: 'Document Debugger', link: '/getting-started/document-debugger' },
          { text: 'Browser-Based Test Harness', link: '/getting-started/test-harness' },
          { text: 'Deploying to Production', link: '/getting-started/deploying-to-production' },
          { text: 'Primitive Stack Overview', link: '/getting-started/stack-overview' },
          { text: 'Is Primitive Right for You?', link: '/getting-started/good-and-bad-apps' },
        ],
        collapsed: false,
      },
      {
        text: 'Reference',
        items: buildReferenceSidebar(readGeneratedReferenceTree()),
        collapsed: false,
      },
    ],

    socialLinks: [{ icon: 'github', link: 'https://github.com/Primitive-Labs/primitive-docs' }],
  },
})


